<a href="https://colab.research.google.com/github/hiderbrandon/BackendDesarrollo1/blob/master/project/part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#SIMULACION Y COMPUTACION NUMERICA
Hider Brandon Vargas Cordoba 1740421

###Needed Packages


In [1]:
# First, import PyTorch
import torch

##First submit

###**Activation** Function

In [4]:
def activation(x):
    """ Sigmoid activation function

        Arguments
        ---------
        x: torch.Tensor
    """

    return 1/(1+torch.exp(-x))

###One Neuron Exercise

####**Exercise**:
Calculate the output of the network with input features features, weights weights, and bias bias. Similar to Numpy, PyTorch has a torch.sum() function, as well as a .sum() method on tensors, for taking sums. Use the function activation defined above as the activation function.

Calculate the output of this network using the weights and bias tensors


In [2]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [7]:
h= torch.sum(features*weights)+ bias
activation(h)

tensor([[0.1595]])

####**Exercise:**
Calculate the output of our little network using matrix multiplication.



In [15]:
h1= torch.mm(features, torch.transpose(weights , 0 ,1))+ bias
activation(h1)

tensor([[0.1595]])

###Simple Multilayer Network

In [16]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

####**Exercise:**
Calculate the output for this multi-layer network using the weights W1 & W2, and the biases, B1 & B2.



In [22]:
layer2 = activation(torch.mm(features , W1)+ B1)
layer3 =  activation(torch.mm(layer2, W2) + B2)

print(layer3)

tensor([[0.3171]])
